### ISSUE TITLE
What if there's no DOI?

### ISSUE THREAD

**Issue by bjohas** [Guillawme/zotero-doi-link-quickcopy#1]
@Guillawme - thank you for sharing (as a follow-up from
https://github.com/willsALMANJ/Zutilo/issues/129#).

My (cursory) understanding is that not all items have DOIs. So you might want something like this:
```
if ('DOI' in item) {
  if (item.DOI) {
        var doiLink = "https://doi.org/" + item.DOI + "\n";
        Zotero.write(doiLink);
  }
}
```

**Comment by Guillawme** [comment]
Very good point, thank you. I started with the very simple export translator template from the Zotero documentation, without thinking about corner cases (very few items in my Zotero library don't have a DOI).

I will fix it soon.

**Comment by Guillawme** [comment]
Related to this issue, I just saw that all item types will soon have a DOI field: https://twitter.com/zotero/status/1413209362206806017

The fix to this issue is still relevant to handle an empty DOI field though, so I won't modify the code.
