### ISSUE TITLE
DOI may be hiding in extra

### ISSUE THREAD

**Issue by bjohas** [Guillawme/zotero-doi-link-quickcopy#2]
The DOI may be in the extra field. You might want to add something like:
```
if (!('DOI' in item)) {
if ('extra' in item) {
  if (item.extra) {
    // Match DOI\:\s*(\S+)
    ...
  }
}
}
```
(Though a new version of Zotero may have a DOI for all item types, so may not be worth fixing.)

**Comment by Guillawme** [comment]
This is a good suggestion, thank you. But I don't have any items with a DOI in the `extra` field in my library and the translator already solves my problem. I cannot make any time commitment to work further on this translator, so I won't include this suggestion. I chose the MIT license precisely to allow anybody to fork and make their own improved version, and I encourage you to do so if this translator is helpful to you.

**Comment by Guillawme** [comment]
This will fix itself in an upcoming update of Zotero, see https://github.com/Guillawme/zotero-doi-link-quickcopy/issues/1#issuecomment-882020710
