### ISSUE TITLE
FYI: the number of QuickCopy functions can be higher than two

### ISSUE THREAD

**Issue by benthamite** [Guillawme/zotero-doi-link-quickcopy#3]
Thanks for creating this repository.

The step (6) of the instructions says that "if you already use both, you'll have to make a decision regarding which one to overwrite". In fact, you can create arbitrarily many QuickCopy functions by setting `extensions.zutilo.copyItems_alt_total` to the desired number. I already had two QuickCopy functions set and was still able to add a new one for the DOI.

**Comment by Guillawme** [comment]
Thank you for letting me know! I updated the README to indicate this possibility.
Glad this function is useful to you too. 😃
